-- Vanished API PostgreSQL baseline schema.
-- Development mode: this file represents the current canonical schema.
-- No version table, version inserts or ALTER-based historical patches are kept.
-- Zero-Knowledge contract: stores only public keys, verifier/hash material,
-- encrypted envelopes and token hashes. It must never store plaintext passwords,
-- private keys, master keys, recovery keys or plaintext messages.

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    full_name VARCHAR(100) NOT NULL DEFAULT '',
    email VARCHAR(254) NOT NULL,
    identity_public_key TEXT NOT NULL,
    key_version INTEGER NOT NULL DEFAULT 1,
    recovery_key_hash VARCHAR(128) NOT NULL,
    avatar_blob BYTEA NULL,
    avatar_mime VARCHAR(100) NULL,
    bio VARCHAR(160) NOT NULL DEFAULT '',
    mfa_totp_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    account_pin_hash VARCHAR(128) NULL,
    account_pin_salt VARCHAR(64) NULL,
    account_pin_failed_attempts INTEGER NOT NULL DEFAULT 0,
    account_pin_locked_until TIMESTAMPTZ NULL,
    account_pin_updated_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_users_username ON users (username);
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email ON users (email);
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email_lower_unique ON users (LOWER(email));
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_recovery_key_hash ON users (recovery_key_hash);
CREATE INDEX IF NOT EXISTS ix_users_username ON users (username);
CREATE INDEX IF NOT EXISTS ix_users_email ON users (email);
CREATE INDEX IF NOT EXISTS ix_users_email_lower ON users (LOWER(email));
CREATE INDEX IF NOT EXISTS ix_users_username_lower ON users (LOWER(username));
CREATE INDEX IF NOT EXISTS ix_users_account_pin_lock ON users (account_pin_locked_until)
    WHERE account_pin_locked_until IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_users_pin_configured ON users (id)
    WHERE account_pin_hash IS NOT NULL;

-- Drop legacy columns that are no longer consumed by the API/client.
ALTER TABLE users DROP COLUMN IF EXISTS totp_secret_ciphertext;

CREATE TABLE IF NOT EXISTS devices (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id VARCHAR(64) NOT NULL,
    public_key TEXT NOT NULL,
    encryption_public_key TEXT NOT NULL DEFAULT '',
    name VARCHAR(100) NOT NULL DEFAULT 'Desktop',
    platform VARCHAR(200) NOT NULL DEFAULT 'unknown',
    is_trusted BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen_at TIMESTAMPTZ NULL,
    revoked_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS ix_devices_user_id ON devices (user_id);
CREATE INDEX IF NOT EXISTS ix_devices_device_id ON devices (device_id);
CREATE INDEX IF NOT EXISTS ix_devices_user_revoked ON devices (user_id, revoked_at);
CREATE INDEX IF NOT EXISTS ix_devices_active_by_user ON devices (user_id, revoked_at, device_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_devices_user_device_id ON devices (user_id, device_id);

CREATE TABLE IF NOT EXISTS auth_challenges (
    id VARCHAR(64) PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id VARCHAR(64) NOT NULL,
    server_nonce VARCHAR(128) NOT NULL,
    purpose VARCHAR(50) NOT NULL DEFAULT 'login',
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_auth_challenges_user_id ON auth_challenges (user_id);
CREATE INDEX IF NOT EXISTS ix_auth_challenges_device_id ON auth_challenges (device_id);
CREATE INDEX IF NOT EXISTS ix_auth_challenges_expires_at ON auth_challenges (expires_at);
CREATE INDEX IF NOT EXISTS ix_auth_challenges_user_device_used ON auth_challenges (user_id, device_id, used_at);
CREATE INDEX IF NOT EXISTS ix_auth_challenges_active ON auth_challenges (user_id, device_id, purpose, used_at, expires_at);


CREATE TABLE IF NOT EXISTS email_verification_challenges (
    id VARCHAR(64) PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    purpose VARCHAR(50) NOT NULL DEFAULT 'registration',
    code_hash VARCHAR(128) NOT NULL,
    code_salt VARCHAR(64) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    expires_at TIMESTAMPTZ NOT NULL,
    verified_at TIMESTAMPTZ NULL,
    used_at TIMESTAMPTZ NULL,
    user_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sent_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS ix_email_verification_email ON email_verification_challenges (email);
CREATE INDEX IF NOT EXISTS ix_email_verification_user_id ON email_verification_challenges (user_id);
CREATE INDEX IF NOT EXISTS ix_email_verification_expires_at ON email_verification_challenges (expires_at);
CREATE INDEX IF NOT EXISTS ix_email_verification_email_active
    ON email_verification_challenges (email, purpose, used_at, expires_at);

CREATE TABLE IF NOT EXISTS refresh_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id VARCHAR(64) NOT NULL,
    family_id VARCHAR(64) NOT NULL,
    token_hash VARCHAR(128) NOT NULL,
    replaced_by_hash VARCHAR(128) NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_refresh_sessions_user_id ON refresh_sessions (user_id);
CREATE INDEX IF NOT EXISTS ix_refresh_sessions_device_id ON refresh_sessions (device_id);
CREATE INDEX IF NOT EXISTS ix_refresh_sessions_family_id ON refresh_sessions (family_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_refresh_sessions_token_hash ON refresh_sessions (token_hash);
CREATE INDEX IF NOT EXISTS ix_refresh_sessions_expires_at ON refresh_sessions (expires_at);
CREATE INDEX IF NOT EXISTS ix_refresh_sessions_user_device_active ON refresh_sessions (user_id, device_id, revoked_at);
CREATE INDEX IF NOT EXISTS ix_refresh_sessions_exp_revoked ON refresh_sessions (expires_at, revoked_at);
CREATE INDEX IF NOT EXISTS ix_refresh_sessions_active_family ON refresh_sessions (user_id, device_id, family_id, revoked_at, expires_at);

CREATE TABLE IF NOT EXISTS key_envelopes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id VARCHAR(64) NOT NULL,
    envelope_type VARCHAR(50) NOT NULL,
    ciphertext_b64 TEXT NOT NULL,
    nonce_b64 VARCHAR(64) NOT NULL,
    kdf JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_key_envelopes_user_id ON key_envelopes (user_id);
CREATE INDEX IF NOT EXISTS ix_key_envelopes_device_id ON key_envelopes (device_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_key_envelopes_user_device_type
    ON key_envelopes (user_id, device_id, envelope_type);


CREATE TABLE IF NOT EXISTS message_threads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_low_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    user_high_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    initiator_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recipient_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    accepted_at TIMESTAMPTZ NULL,
    rejected_at TIMESTAMPTZ NULL,
    CONSTRAINT ck_message_threads_status CHECK (status IN ('pending','accepted','rejected')),
    CONSTRAINT ck_message_threads_pair CHECK (user_low_id < user_high_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_message_threads_pair ON message_threads (user_low_id, user_high_id);
CREATE INDEX IF NOT EXISTS ix_message_threads_recipient_status ON message_threads (recipient_id, status);
CREATE INDEX IF NOT EXISTS ix_message_threads_initiator_status ON message_threads (initiator_id, status);
CREATE INDEX IF NOT EXISTS idx_conversations_user_low_updated ON message_threads (user_low_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_conversations_user_high_updated ON message_threads (user_high_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_message_requests_recipient ON message_threads (recipient_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS private_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT NULL REFERENCES message_threads(id) ON DELETE SET NULL,
    sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recipient_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    sender_device_id VARCHAR(64) NOT NULL,
    recipient_device_id VARCHAR(64) NULL,
    eph_pub_b64 TEXT NOT NULL,
    nonce_b64 VARCHAR(64) NOT NULL,
    ciphertext_b64 TEXT NOT NULL,
    sender_eph_pub_b64 TEXT NULL,
    sender_nonce_b64 VARCHAR(64) NULL,
    sender_ciphertext_b64 TEXT NULL,
    client_msg_id VARCHAR(64) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    read_at TIMESTAMPTZ NULL,
    deleted_for_everyone_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS ix_private_messages_thread_id ON private_messages (thread_id);
CREATE INDEX IF NOT EXISTS ix_private_messages_sender_id ON private_messages (sender_id);
CREATE INDEX IF NOT EXISTS ix_private_messages_recipient_id ON private_messages (recipient_id);
CREATE INDEX IF NOT EXISTS ix_private_messages_created_at ON private_messages (created_at);
CREATE INDEX IF NOT EXISTS idx_pm_pair_id ON private_messages (sender_id, recipient_id, id);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON private_messages (thread_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_private_messages_pair_created ON private_messages (sender_id, recipient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_msg_conv_created ON private_messages (thread_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS ux_private_messages_sender_client_msg_id
    ON private_messages (sender_id, client_msg_id)
    WHERE client_msg_id IS NOT NULL;

-- Drop legacy message columns that were only written as metadata or never updated/read.
ALTER TABLE private_messages DROP COLUMN IF EXISTS sender_key_version;
ALTER TABLE private_messages DROP COLUMN IF EXISTS recipient_key_version;
ALTER TABLE private_messages DROP COLUMN IF EXISTS delivered_at;

CREATE TABLE IF NOT EXISTS deleted_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message_id BIGINT NOT NULL REFERENCES private_messages(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_deleted_messages_user_id ON deleted_messages (user_id);
CREATE INDEX IF NOT EXISTS ix_deleted_messages_message_id ON deleted_messages (message_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_deleted_messages_user_message ON deleted_messages (user_id, message_id);

CREATE TABLE IF NOT EXISTS user_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    blocked_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_user_blocks_blocker_id ON user_blocks (blocker_id);
CREATE INDEX IF NOT EXISTS ix_user_blocks_blocked_id ON user_blocks (blocked_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_user_blocks_pair ON user_blocks (blocker_id, blocked_id);

CREATE TABLE IF NOT EXISTS encrypted_exports (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id VARCHAR(64) NOT NULL,
    ciphertext_b64 TEXT NOT NULL,
    nonce_b64 VARCHAR(64) NOT NULL,
    manifest JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_encrypted_exports_user_id ON encrypted_exports (user_id);
CREATE INDEX IF NOT EXISTS ix_encrypted_exports_device_id ON encrypted_exports (device_id);


CREATE TABLE IF NOT EXISTS security_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(80) NOT NULL,
    outcome VARCHAR(20) NOT NULL,
    user_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
    device_id VARCHAR(64) NULL,
    subject_hash VARCHAR(64) NULL,
    ip_hash VARCHAR(64) NULL,
    user_agent_hash VARCHAR(64) NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_security_audit_events_event_type ON security_audit_events (event_type);
CREATE INDEX IF NOT EXISTS ix_security_audit_events_outcome ON security_audit_events (outcome);
CREATE INDEX IF NOT EXISTS ix_security_audit_events_user_id ON security_audit_events (user_id);
CREATE INDEX IF NOT EXISTS ix_security_audit_events_subject_hash ON security_audit_events (subject_hash);
CREATE INDEX IF NOT EXISTS ix_security_audit_events_ip_hash ON security_audit_events (ip_hash);
CREATE INDEX IF NOT EXISTS ix_security_audit_events_created_at ON security_audit_events (created_at);
CREATE INDEX IF NOT EXISTS idx_security_audit_events_user_created ON security_audit_events (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_audit_events_type_created ON security_audit_events (event_type, created_at DESC);

CREATE TABLE IF NOT EXISTS contact_identity_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    peer_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    peer_key_version INTEGER NOT NULL,
    peer_identity_fingerprint VARCHAR(255) NOT NULL,
    verified_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revoked_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS ix_contact_identity_verifications_user_id ON contact_identity_verifications (user_id);
CREATE INDEX IF NOT EXISTS ix_contact_identity_verifications_peer_id ON contact_identity_verifications (peer_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_contact_identity_verifications_pair ON contact_identity_verifications (user_id, peer_id);
CREATE INDEX IF NOT EXISTS idx_contact_identity_verifications_user_peer ON contact_identity_verifications (user_id, peer_id);
